"""empty message

Revision ID: 49daaf398b78
Revises: 
Create Date: 2024-03-24 10:05:01.035483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49daaf398b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email_address', sa.String(length=70), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('user')
    # ### end Alembic commands ###
