"""empty message

Revision ID: 6512107c9da3
Revises: 6e357b82f3ce
Create Date: 2024-03-24 14:06:56.165018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6512107c9da3'
down_revision = '6e357b82f3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('profile_user_token_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profile_user_token_fkey', 'user', ['user_token'], ['id'])

    # ### end Alembic commands ###
